### ISSUE TITLE
Exclude non stoppable instances and put error in desc

### ISSUE THREAD

**Issue by wahlfeld** [rightscale/policies#11]
`The HTTP request 'POST https://telstra-10.rightscale.com/api/clouds/8/instances/3RP86UHR1PSTN/stop' returned a response with status code '422', expected 2xx. Response body was:
      The instance is not stoppable -- it is not volume based.`

**Comment by flaccid** [comment]
For stop/start scheduler. Exclude locked and non-stoppable instances e.g. instance store.

**Comment by dfrankel33** [comment]
Tracked internally as PSASSET-754
