### ISSUE TITLE
Tag Checker Policy: Policy tag checker runs very long and abort when there are many resources and tags

### ISSUE THREAD

**Issue by kramfs** [rightscale/policies#31]
We are seeing an issue the policy checker when there are many resources and tags and the number to match is more than 3 tags.

Basically, the behavior is the CloudApp is stuck in the launching status for ~6 hours and then aborts **without any error** message. As per Engineering, this is because it is hitting the maximum allowed run time (CWF) for a single CloudApp.

As a comparison, I ran the policy checker in the services account with around 95 instances and tested with 4/5/6/7 tags and every test completed successfully. Though take note, not all instances have tags, only around 1/3 have tags and they usually have average 4 tags each. As for the customer account, Global Subscription, as of this time, have around 833 instances and each has around 12 tags. So that's the difference, in the number of resources.

We have access to the target account, we can also request any PS team access member if you require one for testing.

@rshade requested to file this bug and we are tracking this via this ticket
https://rightscale.zendesk.com/agent/tickets/140583

**Comment by dfrankel33** [comment]
@kramfs can you re-test with this and advise the results? https://github.com/rightscale/policies/blob/git_issue_31/tags/tag_checker_policy/tag_checker_concurrent.cat.rb

**Comment by kramfs** [comment]
@dfrankel33 still no dice, same issue. Added test results in  _PSASSET-737_

**Comment by dfrankel33** [comment]
Fixed with #34

**Comment by kramfs** [comment]
BAT is reporting this issue again using the latest revision below:
https://github.com/rightscale/policies/commit/b3031aa34ea864212b07953a8aa72aaad2d12351

The behavior is exactly the same as this one but sometimes it result in 422 error. More details in the ticket https://rightscale.zendesk.com/agent/tickets/146282
