### ISSUE TITLE
Latest rev of the tag checker policy (b3031aa) failed without any indication why it failed 

### ISSUE THREAD

**Issue by kramfs** [rightscale/policies#73]
### Policy Name
Tag Checker Policy

### Issue Type
[Bug]
Running the tag checker policy against certain tags result in a failed execution after running for a few minutes. There's nothing in the CloudApp audit which indicate what could be the issue

The user is using the b3031aa revision:

This looks similar to the issue I reported in https://github.com/rightscale/policies/issues/31 and could be a regression.

This revision which they have been using all along still works and does not show the behavior of the newer revision
https://github.com/rightscale/policies/blob/Week-of-11-13-2017/tags/tag_checker_policy/tag_checker.cat.rb

### Policy version (Bug Only)
[Version of Policy in use, this can be found in the long_description]
1.4

### Parameter Values (Bug Only)
[Please provide the parameter values used when launching the Policy CloudApp]
azure:CUST-CODE,azure:REGION,azure:COUNTRY-DEPT,azure:CHARGING-TYPE

### Error Messages (Bug Only)
[Provide any error messages returned (if applicable)]
On most of the test executions, there was no error message. On some rare case, it resulted in a 422 response. More details in the ticket https://rightscale.zendesk.com/agent/tickets/146282

**Comment by dfrankel33** [comment]
Tracked internally as PSASSET-799
